spring:
  datasource:
    url: jdbc:postgresql://dpg-cnqdkja1hbls739a8cn0-a.frankfurt-postgres.render.com:5432/timelinear_db
    username: timelinear_db_user
    password: W9zowBjyGVWaadGTcEIEQqg9UVSIZQxb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days